before_script:
    - apt-get update
    - apt-get install --force-yes -y software-properties-common apt-transport-https
    - add-apt-repository -y 'deb http://debian.jpleau.ca/ jessie-backports main contrib non-free'
    - apt-get update -qq
    - apt-get install --force-yes -y autoconf automake make libx11-dev libpango1.0-dev libcairo2-dev libstartup-notification0-dev libxcb-icccm4-dev libxcb-util0-dev libxcb-xinerama0-dev libxcb-xkb-dev libx11-xcb-dev
    - apt-get install --force-yes -y libxcb1-dev xvfb discount xdotool fluxbox libxkbcommon-dev libxkbcommon-x11-dev libxcb-ewmh-dev xutils-dev libtool lcov
    - git clone --recursive https://github.com/Airblader/xcb-util-xrm.git
    - cd xcb-util-xrm 
    - ./autogen.sh --prefix=/usr
    - make
    - sudo make install
    - cd -

build-rofi:
    script:
        - git submodule update --init
        - autoreconf -i
        - ./configure --enable-gcov
        - make
        - make check
        - make distcheck
        - make coverage
