name: Rofi
description: A window switcher, run dialog and dmenu replacement
github-url: https://github.com/DaveDavenport/rofi
github-user-url: https://github.com/DaveDavenport/
github-user: Dave Davenport
